const fs = require('fs');
const lines = [];
lines.push('/*');
lines.push(' * T10R - Wastage / Breakage / Other stock adjustments.');
lines.push(' *');
lines.push(' * Uses the EXISTING inventory_movements ledger and createInventoryMovement');
lines.push(' * path. No new tables, no new ledger, no new permissions, no separate');
lines.push(' * inventory system. Decreases require a canonical reason (Wastage /');
lines.push(' * Breakage / Other); increases keep the existing free-text/optional');
lines.push(' * behaviour.');
lines.push(' *');
lines.push(' *   node --test tests/wastage.test.mjs');
lines.push(' */');
lines.push('import crypto from "node:crypto";');
lines.push('import pg from "pg";');
lines.push('import bcrypt from "bcryptjs";');
lines.push('import assert from "node:assert/strict";');
lines.push('import test from "node:test";');
lines.push('import express from "express";');
lines.push('import inventoryRt from "../routes/inventory.js";');
lines.push('import reportsRt from "../routes/reports.js";');
lines.push('import { resolveAdjustmentReason, classifyAdjustmentReason, ADJUSTMENT_REASONS } from "../services/adjustmentReasons.js";');
lines.push('');
lines.push('/* ----------------------------------------------------- test database setup */');
lines.push('');
lines.push('const createTestDb = async () => {');
lines.push('  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } });');
lines.push('  const db = (q, p) => pool.query(q, p);');
lines.push('  const tag = crypto.randomUUID().slice(0, 8);');
lines.push('  const company = await db(`INSERT INTO companies(name) VALUES($1) RETURNING id`, [`wastage-${tag}`]);');
lines.push('  const companyId = company.rows[0].id;');
lines.push('  const store = await db(`INSERT INTO stores(company_id, name) VALUES($1, $2) RETURNING id`, [companyId, `wastage-store-${tag}`]);');
lines.push('  const storeId = store.rows[0].id;');
lines.push('  const role = await db(`INSERT INTO roles(company_id,name) VALUES($1,$2) RETURNING id`, [companyId, `operator-${tag}`]);');
lines.push('  const adminRole = await db(`INSERT INTO roles(company_id,name) VALUES($1,$2) RETURNING id`, [companyId, `admin-${tag}`]);');
lines.push('  const user = await db(');
lines.push('    `INSERT INTO users(company_id,store_id,role_id,username,full_name,password_hash) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,company_id,store_id,role_id`,');
lines.push('    [companyId, storeId, role.rows[0].id, `op-${tag}`, `Operator ${tag}`, await bcrypt.hash("pass", 10)]');
lines.push('  );');
lines.push('  const adminUser = await db(');
lines.push('    `INSERT INTO users(company_id,store_id,role_id,username,full_name,password_hash) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,company_id,store_id,role_id`,');
lines.push('    [companyId, storeId, adminRole.rows[0].id, `admin-${tag}`, `Admin ${tag}`, await bcrypt.hash("pass", 10)]');
lines.push('  );');
lines.push('  const cat = await db(`INSERT INTO categories(company_id,name) VALUES($1,$2) RETURNING id`, [companyId, `WastageTest-${tag}`]);');
lines.push('  const products = await Promise.all(');
lines.push('    [');
lines.push('      { name: "Test Product A", stock: 10, tracked: true },');
lines.push('      { name: "Test Product B", stock: 5, tracked: true },');
lines.push('    ].map(({ name, stock, tracked }) =>');
lines.push('      db(');
lines.push('        `INSERT INTO products(company_id,category_id,name,sku,price,cost_price,vat_rate,vat_applicable,stock_quantity,low_stock_level,track_stock,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,true) RETURNING id,name,stock_quantity,track_stock`,');
lines.push('        [companyId, cat.rows[0].id, name, `SKU-${crypto.randomUUID().slice(0, 8)}`, 10, 4, 20, true, stock, 5, tracked]');
lines.push('      )');
lines.push('    )');
lines.push('  );');
lines.push('  return { pool, db, role, adminRole, user, adminUser, cat, products, companyId, storeId, company, store };');
lines.push('};');

fs.writeFileSync('C:/Users/cc/Desktop/onePOS/tests/wastage.test.mjs', lines.join('\n'));
console.log('Part 1 written');