import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const read=(p)=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
test("hospitality and KDS install registered operational pages",()=>{const s=read("services/packageRegistry.js");assert.match(s,/runtimeComponent: "hospitality_operations"/);assert.match(s,/runtimeComponent: "kitchen_display"/);assert.match(s,/INSERT INTO platform_pages/)});
test("custom page runtime resolves registered hospitality components",()=>{const s=read("src/components/CustomPageRuntime.jsx");assert.match(s,/runtime_component === "hospitality_operations"/);assert.match(s,/runtime_component === "kitchen_display"/)});
test("hospitality page supports floor plan and reservations",()=>{const s=read("src/pages/hospitality/HospitalityOperations.jsx");assert.match(s,/hospitality\/floors/);assert.match(s,/hospitality\/tables/);assert.match(s,/hospitality\/reservations/)});
test("KDS uses canonical ticket statuses",()=>{const s=read("src/pages/hospitality/KitchenDisplay.jsx");assert.match(s,/NEW:\s*"IN_PREPARATION"/);assert.match(s,/IN_PREPARATION:\s*"READY"/);assert.match(s,/READY:\s*"COMPLETED"/)});
test("hospitality tables expose current bill and occupancy lifecycle",()=>{const s=read("routes/hospitality.js");assert.match(s,/current_bill/);assert.match(s,/open_order_count/);assert.match(s,/OCCUPIED/);assert.match(s,/\["EMPTY", "RESERVED", "OCCUPIED"\]/)});
test("hospitality UI renders real QR codes and table bill",()=>{const s=read("src/pages/hospitality/HospitalityOperations.jsx");assert.match(s,/QRCodeWriter/);assert.match(s,/Table ordering QR/);assert.match(s,/current_bill/);assert.match(s,/setTableStatus/)});
test("operational app is installable as a standalone PWA",()=>{const html=read("app/index.html"),manifest=read("public/app/manifest.webmanifest"),sw=read("public/app/offline-sw.js");assert.match(html,/manifest\.webmanifest/);assert.match(manifest,/"display": "standalone"/);assert.match(manifest,/"scope": "\/app\/"/);assert.match(sw,/onepos-till-shell-v3/)});
