import express from "express";
import jwt from "jsonwebtoken";

/*
 * T10D — Self-Checkout mode foundation.
 *
 * A restricted till mode entered explicitly from the staff POS. Reuses the
 * EXISTING authentication (same JWT/session layer via services/session.js)
 * and the EXISTING permissions model — no second user/permission system:
 *
 *   - Entering requires `sale.create` (admin/owner roles pass via
 *     canViewCompanyCustomers, exactly like every other route).
 *   - The mode token is a SHORT-LIVED JWT signed with the server's existing
 *     secret. It carries the same company/store/role identity as the
 *     operator's session, so every downstream query keeps its normal tenant
 *     and store scoping. The browser cannot choose a company/store — the
 *     token's claims are copied server-side from the authenticated user.
 *   - requireSelfCheckoutMode blocks any privileged operation performed with
 *     a self-checkout mode token (operator-only functions), and the sale
 *     route rejects cash payments from self-checkout sessions.
 *
 * The mode token is OPTIONAL: normal POS tokens continue to work exactly as
 * today. Self-checkout mode only ever RESTRICTS what a token may do.
 */

const SCO_MODE_TTL = process.env.SCO_MODE_TTL || "12h";

export function createSelfCheckoutRouter({
  authenticate,
  authorize,
  db,
  bcrypt = null,
  jwtSecret = process.env.JWT_SECRET || "development-secret-change-this",
  modeTtl = SCO_MODE_TTL,
  writeAudit = null,
  requireSelfCheckoutEntitlement = null,
  getCompanyEntitlements = null,
}) {
  const router = express.Router();

  const signModeToken = (user) =>
    jwt.sign(
      {
        id: user.id,
        companyId: user.companyId,
        storeId: user.storeId,
        roleId: user.roleId,
        username: user.username,
        mode: "self_checkout",
      },
      jwtSecret,
      { expiresIn: modeTtl }
    );

  /*
   * POST /api/self-checkout/session
   * Explicitly enter Self-Checkout mode for this device/session.
   * Authorised with the SAME permission used to create sales.
   */
  router.post(
    "/self-checkout/session",
    authenticate,
    ...(requireSelfCheckoutEntitlement ? [requireSelfCheckoutEntitlement] : []),
    authorize("sale.create"),
    async (req, res) => {
      try {
        // The mode is tied to the authenticated operator's own store/company.
        const store = await db(
          `SELECT s.id, s.name FROM stores s WHERE s.id = $1 AND s.company_id = $2 AND s.active = true`,
          [req.user.storeId, req.user.companyId]
        );
        if (!store.rows.length) {
          return res.status(403).json({
            success: false,
            message: "Self-Checkout is not available for this store",
          });
        }

        const modeToken = signModeToken(req.user);

        if (typeof writeAudit === "function") {
          Promise.resolve(
            writeAudit(req.user.companyId, req.user.id, "SELF_CHECKOUT_MODE_STARTED", "self_checkout_session", null, {
              storeId: req.user.storeId,
            })
          ).catch(() => {});
        }

        res.status(201).json({
          success: true,
          message: "Self-Checkout mode started",
          data: {
            modeToken,
            store: { id: store.rows[0].id, name: store.rows[0].name },
            mode: "self_checkout",
          },
        });
      } catch (error) {
        console.error("Start self-checkout mode error:", error);
        res.status(500).json({ success: false, message: "Unable to start Self-Checkout mode" });
      }
    }
  );

  /*
   * DELETE /api/self-checkout/session
   * Leave Self-Checkout mode. The token is simply discarded client-side;
   * this endpoint exists so the exit is an explicit, auditable action.
   */
  router.delete(
    "/self-checkout/session",
    authenticate,
    ...(requireSelfCheckoutEntitlement ? [requireSelfCheckoutEntitlement] : []),
    authorize("sale.create"),
    async (req, res) => {
      if (typeof writeAudit === "function") {
        Promise.resolve(
          writeAudit(req.user.companyId, req.user.id, "SELF_CHECKOUT_MODE_EXITED", "self_checkout_session", null, {
            storeId: req.user.storeId,
          })
        ).catch(() => {});
      }
      res.json({ success: true, message: "Self-Checkout mode ended" });
    }
  );

  /*
   * POST /api/self-checkout/device-session
   *
   * Customer-facing entry (login screen → Self-Checkout). NO staff session is
   * required: the device proves itself with the store's Self-Checkout device
   * key (generated by an Admin/Owner in Settings → Store & Till; stored as a
   * bcrypt hash on the store row). A valid key mints the SAME restricted
   * short-lived mode token the staff flow uses — the browser still cannot
   * choose a company/store (they come from the store row that owns the key),
   * and the mode gate keeps blocking every privileged operation.
   */
  router.post("/self-checkout/device-session", async (req, res) => {
    try {
      if (typeof bcrypt?.compare !== "function") {
        return res.status(500).json({ success: false, message: "Server is not configured for device pairing" });
      }
      const deviceKey = String(req.body?.deviceKey || "").trim();
      if (!deviceKey || deviceKey.length > 200) {
        return res.status(400).json({ success: false, message: "Enter the Self-Checkout device key" });
      }

      /* Only stores that were explicitly paired can mint a session. */
      const candidates = await db(
        `SELECT id, company_id, name, self_checkout_key_hash FROM stores WHERE active = true AND self_checkout_key_hash IS NOT NULL`
      );
      let pairedStore = null;
      for (const store of candidates.rows) {
        if (await bcrypt.compare(deviceKey, store.self_checkout_key_hash)) {
          pairedStore = store;
          break;
        }
      }
      if (!pairedStore) {
        return res.status(401).json({ success: false, message: "Invalid Self-Checkout device key" });
      }
      if (typeof getCompanyEntitlements === "function") {
        const entitlements = await getCompanyEntitlements(pairedStore.company_id);
        if (entitlements.self_checkout !== true) {
          return res.status(403).json({ success: false, code: "FEATURE_NOT_LICENSED", message: "Self-Checkout is not licensed for this company" });
        }
      }

      /* sales.user_id is NOT NULL and the mode token carries an operator
         identity, so a device session acts as the store's designated
         operator account: prefer an Admin/Owner, else any active user of
         the company. The mode gate still restricts the token to basket +
         card sale operations only. */
      const admins = await db(
        `SELECT u.id, u.role_id, u.username FROM users u
         JOIN roles r ON r.id = u.role_id
         WHERE u.company_id = $1 AND u.active = true AND LOWER(r.name) IN ('administrator','admin','owner')
         ORDER BY u.created_at LIMIT 1`,
        [pairedStore.company_id]
      );
      const operator = admins.rows.length
        ? admins.rows[0]
        : (await db(
          `SELECT u.id, u.role_id, u.username FROM users u WHERE u.company_id = $1 AND u.active = true ORDER BY u.created_at LIMIT 1`,
          [pairedStore.company_id]
        )).rows[0];
      if (!operator) {
        return res.status(409).json({ success: false, message: "This store has no active staff account — ask an administrator to add one" });
      }

      const modeToken = jwt.sign(
        {
          id: operator.id,
          companyId: pairedStore.company_id,
          storeId: pairedStore.id,
          roleId: operator.role_id,
          username: operator.username,
          mode: "self_checkout",
        },
        jwtSecret,
        { expiresIn: modeTtl }
      );

      if (typeof writeAudit === "function") {
        Promise.resolve(
          writeAudit(pairedStore.company_id, operator.id, "SELF_CHECKOUT_DEVICE_SESSION_STARTED", "self_checkout_session", null, {
            storeId: pairedStore.id,
          })
        ).catch(() => {});
      }

      res.status(201).json({
        success: true,
        message: "Self-Checkout device session started",
        data: {
          modeToken,
          store: { id: pairedStore.id, name: pairedStore.name },
          mode: "self_checkout",
        },
      });
    } catch (error) {
      console.error("Self-Checkout device session error:", error);
      res.status(500).json({ success: false, message: "Unable to start Self-Checkout" });
    }
  });

  /*
   * POST /api/self-checkout/customer-lookup
   * Optional customer identification from the Self-Checkout screen: the
   * customer enters their own phone or email; an exact, company-scoped match
   * returns ONLY id + name (loyalty/receipts attach to the sale). No match →
   * the customer simply continues as a guest. Staff tokens are refused —
   * this endpoint exists solely for the restricted customer session.
   */
  router.post("/self-checkout/customer-lookup", authenticate, async (req, res) => {
    try {
      if (req.user?.mode !== "self_checkout") {
        return res.status(403).json({ success: false, message: "Only available in Self-Checkout mode" });
      }
      const query = String(req.body?.query || "").trim().slice(0, 255);
      if (!query) {
        return res.status(400).json({ success: false, message: "Enter your phone number or email" });
      }
      const digits = query.replace(/[^0-9]/g, "");
      const result = await db(
        `SELECT id, name FROM customers
         WHERE company_id = $1 AND active = true
           AND (LOWER(email) = LOWER($2) OR phone = $2
                OR ($3 <> '' AND REGEXP_REPLACE(COALESCE(phone, ''), '[^0-9]', '', 'g') = $3))
         LIMIT 1`,
        [req.user.companyId, query, digits]
      );
      if (!result.rows.length) {
        return res.status(404).json({ success: false, found: false, message: "We could not find that account — you can continue as a guest" });
      }
      res.json({ success: true, found: true, data: { id: result.rows[0].id, name: result.rows[0].name } });
    } catch (error) {
      console.error("Self-Checkout customer lookup error:", error);
      res.status(500).json({ success: false, message: "Lookup failed — you can continue as a guest" });
    }
  });

  return router;
}

export default createSelfCheckoutRouter;

/*
 * Mode gate middleware factory (wired in server.js ahead of the privileged
 * routers). A token carrying mode:"self_checkout" may only perform the
 * read-only and sale operations Self-Checkout actually needs — and only via
 * the HTTP methods the mode uses. Anything else is refused server-side.
 */
/* path prefix -> allowed methods (empty array = all methods for that prefix) */
const SCO_ALLOWED = [
  { prefix: "/api/sales", methods: ["GET", "POST"] },          // basket pricing lookups + sale creation
  { prefix: "/api/products", methods: ["GET"] },               // product search only — no create/edit/delete
  { prefix: "/api/settings", methods: ["GET"] },               // VAT/store context only — no configuration writes
  { prefix: "/api/self-checkout", methods: ["DELETE", "POST"] }, // auditable exit + customer lookup
];

export function createSelfCheckoutModeGate() {
  return function selfCheckoutModeGate(req, res, next) {
    const header = req.headers.authorization;
    if (!header || !header.startsWith("Bearer ")) return next();

    let payload;
    try {
      payload = jwt.decode(header.substring(7));
    } catch {
      return next();
    }

    if (payload?.mode !== "self_checkout") return next();

    const path = req.originalUrl || req.url || "";
    const method = (req.method || "GET").toUpperCase();
    const allowed = SCO_ALLOWED.some(
      (rule) =>
        (path === rule.prefix || path.startsWith(rule.prefix)) &&
        (rule.methods.length === 0 || rule.methods.includes(method))
    );
    if (allowed) return next();

    return res.status(403).json({
      success: false,
      message: "Not available in Self-Checkout mode",
    });
  };
}
