import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Link, Plus, RefreshCw, Users, X } from "lucide-react";
import { apiRequest } from "../../services/api.js";

const statusLabel = (table) => table.status === "OCCUPIED" ? "Occupied" : table.reservation_status ? "Reserved" : "Empty";
export default function HospitalityOperations() {
  const [floors,setFloors]=useState([]),[tables,setTables]=useState([]),[reservations,setReservations]=useState([]),[floorId,setFloorId]=useState("");
  const [error,setError]=useState(""),[loading,setLoading]=useState(true),[showReservation,setShowReservation]=useState(false),[qr,setQr]=useState(null);
  const [form,setForm]=useState({customerName:"",reservationDate:new Date().toISOString().slice(0,10),reservationTime:"19:00",guests:2,tableId:"",notes:""});
  const load=async()=>{setLoading(true);setError("");try{const [f,t,r]=await Promise.all([apiRequest("/api/hospitality/floors"),apiRequest("/api/hospitality/tables"),apiRequest("/api/hospitality/reservations")]);setFloors(f.data||[]);setTables(t.data||[]);setReservations(r.data||[]);setFloorId(x=>x||f.data?.[0]?.id||"");}catch(e){setError(e.message||"Unable to load hospitality");}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const visible=useMemo(()=>tables.filter(t=>!floorId||t.floor_id===floorId),[tables,floorId]);
  const createQr=async(table)=>{const r=await apiRequest(`/api/hospitality/tables/${table.id}/qr-session`,{method:"POST",body:"{}"});const url=`${window.location.origin}${r.data.path}`;const {QRCodeWriter,BarcodeFormat}=await import("@zxing/library");const matrix=new QRCodeWriter().encode(url,BarcodeFormat.QR_CODE,256,256);let path="";for(let y=0;y<matrix.getHeight();y++)for(let x=0;x<matrix.getWidth();x++)if(matrix.get(x,y))path+=`M${x} ${y}h1v1h-1z`;const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${matrix.getWidth()} ${matrix.getHeight()}" shape-rendering="crispEdges"><rect width="100%" height="100%" fill="white"/><path d="${path}" fill="black"/></svg>`;setQr({table,url,svg});};
  const setTableStatus=async(table,status)=>{await apiRequest(`/api/hospitality/tables/${table.id}`,{method:"PUT",body:JSON.stringify({status})});await load();};
  const reserve=async(e)=>{e.preventDefault();await apiRequest("/api/hospitality/reservations",{method:"POST",body:JSON.stringify({...form,guests:Number(form.guests),tableId:form.tableId||null})});setShowReservation(false);setForm(x=>({...x,customerName:"",tableId:"",notes:""}));await load();};
  if(loading)return <div className="min-h-screen grid place-items-center">Loading hospitality…</div>;
  return <main className="onepos-page-enter min-h-screen bg-slate-100 p-4 md:p-6"><div className="mx-auto max-w-7xl space-y-4">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs text-slate-500">OneHospitality</div><h1 className="text-2xl font-semibold">Floor & Tables</h1></div><div className="flex gap-2"><button className="onepos-btn" onClick={load}><RefreshCw size={16}/> Refresh</button><button className="onepos-btn onepos-btn-primary" onClick={()=>setShowReservation(true)}><Plus size={16}/> Reservation</button></div></header>
    {error&&<div className="onepos-card p-4 text-red-700">{error}</div>}
    <div className="flex gap-2 overflow-x-auto">{floors.map(f=><button key={f.id} onClick={()=>setFloorId(f.id)} className={`onepos-btn ${floorId===f.id?'onepos-btn-primary':''}`}>{f.name} <span className="text-xs opacity-70">{f.table_count}</span></button>)}</div>
    <section className="onepos-card p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{visible.map(t=><article key={t.id} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between gap-2"><div><div className="text-xs text-slate-500">Table</div><div className="text-xl font-semibold">{t.table_number}</div>{t.name&&<div className="text-sm text-slate-500">{t.name}</div>}</div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs h-fit">{statusLabel(t)}</span></div><div className="mt-4 flex items-center gap-2 text-sm text-slate-600"><Users size={15}/>{t.capacity} guests</div><div className="mt-3 grid grid-cols-2 gap-2"><button className="onepos-btn" onClick={()=>createQr(t)}><Link size={14}/> QR</button><button className="onepos-btn" onClick={()=>setTableStatus(t,t.status==="OCCUPIED"?"EMPTY":"OCCUPIED")}>{t.status==="OCCUPIED"?"Clear":"Seat"}</button></div>{Number(t.current_bill)>0&&<div className="mt-2 rounded-xl bg-slate-50 p-2 text-sm"><div className="flex justify-between"><span>Current bill</span><b>£{Number(t.current_bill).toFixed(2)}</b></div><div className="text-xs text-slate-500">{t.open_order_count} open order{Number(t.open_order_count)===1?"":"s"}</div></div>}{t.reservation_time&&<div className="mt-2 flex items-center gap-2 text-sm"><CalendarDays size={15}/>{String(t.reservation_time).slice(0,5)}</div>}</article>)}</div></section>
    <section className="onepos-card p-4"><h2 className="mb-3 font-semibold">Upcoming reservations</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500"><th className="p-2">Date</th><th>Name</th><th>Guests</th><th>Table</th><th>Status</th></tr></thead><tbody>{reservations.map(r=><tr key={r.id} className="border-t"><td className="p-2">{String(r.reservation_date).slice(0,10)} {String(r.reservation_time).slice(0,5)}</td><td>{r.customer_name}</td><td>{r.guests}</td><td>{r.table_number||"—"}</td><td>{r.status}</td></tr>)}</tbody></table></div></section>

    {qr&&<div className="onepos-overlay-backdrop"><section className="onepos-overlay-panel onepos-overlay-square"><header className="onepos-overlay-header"><div><div className="text-xs text-slate-500">Table {qr.table.table_number}</div><h2 className="font-semibold">Table ordering QR</h2></div><button className="onepos-btn" onClick={()=>setQr(null)} aria-label="Close"><X size={16}/></button></header><div className="onepos-overlay-body text-center"><div className="mx-auto w-64 max-w-full rounded-2xl bg-white p-3" dangerouslySetInnerHTML={{__html:qr.svg}}/><p className="mt-3 break-all text-xs text-slate-500">{qr.url}</p><div className="mt-4 grid grid-cols-2 gap-2"><button className="onepos-btn" onClick={()=>navigator.clipboard?.writeText(qr.url)}>Copy link</button><button className="onepos-btn onepos-btn-primary" onClick={()=>window.print()}>Print QR</button></div></div></section></div>}
    {showReservation&&<div className="onepos-overlay-backdrop"><form onSubmit={reserve} className="onepos-overlay-panel onepos-overlay-square"><header className="onepos-overlay-header"><h2 className="font-semibold">New reservation</h2><button type="button" className="onepos-btn" onClick={()=>setShowReservation(false)}>Close</button></header><div className="onepos-overlay-body space-y-3"><label className="onepos-field"><span>Name</span><input className="onepos-control" required value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label className="onepos-field"><span>Date</span><input type="date" className="onepos-control" required value={form.reservationDate} onChange={e=>setForm({...form,reservationDate:e.target.value})}/></label><label className="onepos-field"><span>Time</span><input type="time" className="onepos-control" required value={form.reservationTime} onChange={e=>setForm({...form,reservationTime:e.target.value})}/></label></div><label className="onepos-field"><span>Guests</span><input type="number" min="1" className="onepos-control" value={form.guests} onChange={e=>setForm({...form,guests:e.target.value})}/></label><label className="onepos-field"><span>Table</span><select className="onepos-control" value={form.tableId} onChange={e=>setForm({...form,tableId:e.target.value})}><option value="">Unassigned</option>{tables.map(t=><option key={t.id} value={t.id}>{t.floor_name} · {t.table_number}</option>)}</select></label><label className="onepos-field"><span>Notes</span><textarea className="onepos-control" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="onepos-btn onepos-btn-primary w-full">Save reservation</button></div></form></div>}
  </div></main>;
}
