export const GENERIC_ORDER_STATUSES = {
  RECEIVED: "RECEIVED",
  PREPARING: "PREPARING",
  READY: "READY",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  READY_FOR_DELIVERY: "READY_FOR_DELIVERY",
  COLLECTED: "COLLECTED",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
};

export const FULFILMENT_TYPES = {
  SELF_PICKUP: "SELF_PICKUP",
  DELIVERY: "DELIVERY",
};

function nextGenericStatus(fulfilmentType, currentStatus) {
  switch (currentStatus) {
    case GENERIC_ORDER_STATUSES.RECEIVED:
      return GENERIC_ORDER_STATUSES.PREPARING;
    case GENERIC_ORDER_STATUSES.PREPARING: {
      if (fulfilmentType === FULFILMENT_TYPES.SELF_PICKUP) return GENERIC_ORDER_STATUSES.READY_FOR_PICKUP;
      if (fulfilmentType === FULFILMENT_TYPES.DELIVERY) return GENERIC_ORDER_STATUSES.READY_FOR_DELIVERY;
      return GENERIC_ORDER_STATUSES.READY;
    }
    case GENERIC_ORDER_STATUSES.READY_FOR_PICKUP:
      return GENERIC_ORDER_STATUSES.COLLECTED;
    case GENERIC_ORDER_STATUSES.READY_FOR_DELIVERY:
      return GENERIC_ORDER_STATUSES.COMPLETED;
    case GENERIC_ORDER_STATUSES.READY:
      return GENERIC_ORDER_STATUSES.COMPLETED;
    case GENERIC_ORDER_STATUSES.COLLECTED:
      return GENERIC_ORDER_STATUSES.COMPLETED;
    default:
      return null;
  }
}

const VALID_TRANSITIONS = {
  [GENERIC_ORDER_STATUSES.RECEIVED]: [
    GENERIC_ORDER_STATUSES.PREPARING,
    GENERIC_ORDER_STATUSES.REJECTED,
    GENERIC_ORDER_STATUSES.CANCELLED,
  ],
  [GENERIC_ORDER_STATUSES.PREPARING]: [
    GENERIC_ORDER_STATUSES.READY_FOR_PICKUP,
    GENERIC_ORDER_STATUSES.READY_FOR_DELIVERY,
    GENERIC_ORDER_STATUSES.READY,
    GENERIC_ORDER_STATUSES.CANCELLED,
  ],
  [GENERIC_ORDER_STATUSES.READY_FOR_PICKUP]: [GENERIC_ORDER_STATUSES.COLLECTED, GENERIC_ORDER_STATUSES.CANCELLED],
  [GENERIC_ORDER_STATUSES.READY_FOR_DELIVERY]: [GENERIC_ORDER_STATUSES.COMPLETED, GENERIC_ORDER_STATUSES.CANCELLED],
  [GENERIC_ORDER_STATUSES.READY]: [GENERIC_ORDER_STATUSES.COMPLETED, GENERIC_ORDER_STATUSES.CANCELLED],
  [GENERIC_ORDER_STATUSES.COLLECTED]: [GENERIC_ORDER_STATUSES.COMPLETED],
  [GENERIC_ORDER_STATUSES.COMPLETED]: [],
  [GENERIC_ORDER_STATUSES.REJECTED]: [],
  [GENERIC_ORDER_STATUSES.CANCELLED]: [],
};

export function canTransition(fulfilmentType, fromStatus, toStatus) {
  const allowed = VALID_TRANSITIONS[fromStatus];
  if (!allowed) return false;
  return allowed.includes(toStatus);
}

export function resolveNextStatus(fulfilmentType, currentStatus) {
  return nextGenericStatus(fulfilmentType, currentStatus);
}
