import { useEffect, useState } from "react";
import { FileText, RefreshCw, Search, X } from "lucide-react";
import { apiRequest } from "../../services/api.js";
function SalesAdmin() {
  const [sales, setSales] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [detail, setDetail] = useState(null);
  const load = async () => { try { setLoading(true); setError(""); const data = await apiRequest(`/api/sales${search.trim() ? `?search=${encodeURIComponent(search.trim())}` : ""}`); if (!data.success) throw new Error(data.message); setSales(data.data || []); } catch (err) { setError(err.message || "Unable to load sales"); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [search]);
  const open = async (sale) => { try { const data = await apiRequest(`/api/sales/${sale.id}`); if (!data.success) throw new Error(data.message); setDetail(data.data); } catch (err) { setError(err.message || "Unable to load sale"); } };
  return <div><div className="flex justify-between items-center mb-5"><div><h1 className="text-2xl font-bold">Sales</h1><p className="text-sm text-slate-500 mt-1">Completed and recorded till transactions.</p></div><button onClick={load} className="h-10 px-4 bg-white border rounded-lg text-sm flex items-center gap-2"><RefreshCw size={16} /> Refresh</button></div><div className="bg-white border rounded-xl overflow-hidden"><div className="p-4 border-b"><div className="relative max-w-md"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search sale, customer or ID..." className="w-full h-10 pl-10 pr-3 border rounded-lg text-sm" /></div></div>{loading ? <div className="p-10 text-center text-slate-400">Loading sales...</div> : error ? <div className="p-10 text-center text-red-600">{error}<button onClick={load} className="block mx-auto mt-3 px-4 py-2 bg-blue-600 text-white rounded text-sm">Retry</button></div> : sales.length === 0 ? <div className="p-10 text-center text-slate-400">No sales found.</div> : <div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-slate-50">{["Sale", "Date/time", "Store", "Customer", "Items", "Total", "Payment", "Status", "Cashier"].map((heading) => <th key={heading} className="text-left px-4 py-3 text-xs font-semibold text-slate-500 uppercase">{heading}</th>)}</tr></thead><tbody>{sales.map((sale) => <tr key={sale.id} onClick={() => open(sale)} className="border-t hover:bg-slate-50 cursor-pointer"><td className="px-4 py-3 text-sm font-medium">{sale.receipt_number || sale.id.slice(0, 8)}</td><td className="px-4 py-3 text-xs text-slate-500">{new Date(sale.created_at).toLocaleString()}</td><td className="px-4 py-3 text-sm">{sale.store_name || "-"}</td><td className="px-4 py-3 text-sm">{sale.customer_name}</td><td className="px-4 py-3 text-sm">{sale.item_count}</td><td className="px-4 py-3 text-sm font-semibold">£{Number(sale.total).toFixed(2)}</td><td className="px-4 py-3 text-sm">{sale.payment_method || "-"}</td><td className="px-4 py-3 text-sm">{sale.status}</td><td className="px-4 py-3 text-sm">{sale.cashier || "-"}</td></tr>)}</tbody></table></div>}</div>{detail && <SaleDetailModal sale={detail} onClose={() => setDetail(null)} />}</div>;
}

function SaleDetailModal({ sale, onClose }) {
  return <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-xl w-[760px] max-w-full max-h-[85vh] shadow-2xl flex flex-col"><div className="p-4 border-b flex justify-between"><div><h2 className="font-bold text-lg">Sale {sale.receipt_number || sale.id.slice(0, 8)}</h2><p className="text-xs text-slate-500">{new Date(sale.created_at).toLocaleString()} · {sale.store_name || "-"}</p></div><button onClick={onClose} className="p-2" title="Close"><X size={18} /></button></div><div className="p-4 overflow-auto"><div className="grid grid-cols-2 gap-3 text-sm mb-5"><div>Customer<div className="font-medium">{sale.customer_name || "Walk-in Customer"}</div></div><div>Cashier<div className="font-medium">{sale.cashier || "-"}</div></div><div>Status<div className="font-medium">{sale.status}</div></div><div>Payment<div className="font-medium">{sale.payment_method || "-"} · £{Number(sale.payment_amount || 0).toFixed(2)}</div></div></div><table className="w-full"><thead><tr className="bg-slate-50">{["Product", "Quantity", "Unit price", "Line total"].map((heading) => <th key={heading} className="text-left px-3 py-2 text-xs uppercase text-slate-500">{heading}</th>)}</tr></thead><tbody>{(sale.items || []).map((item) => <tr key={item.id} className="border-t"><td className="px-3 py-2 text-sm">{item.product_name}</td><td className="px-3 py-2 text-sm">{item.quantity}</td><td className="px-3 py-2 text-sm">£{Number(item.unit_price).toFixed(2)}</td><td className="px-3 py-2 text-sm font-semibold">£{Number(item.total).toFixed(2)}</td></tr>)}</tbody></table><div className="text-right mt-5 text-sm">Subtotal £{Number(sale.subtotal).toFixed(2)} · VAT £{Number(sale.tax).toFixed(2)} · Discount £{Number(sale.discount).toFixed(2)} · <strong>Total £{Number(sale.total).toFixed(2)}</strong></div></div></div></div>;
}

export default SalesAdmin;
