import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../../../services/api.js";
import MetadataResourcePicker from "./MetadataResourcePicker.jsx";

const blank=()=>({name:"",objectId:"",active:false,conditions:{type:"all",rules:[]},steps:[{label:"Manager approval",roleId:"",config:{}}],config:{allowReassign:true,requireCommentOnReject:true,lockRecord:true,submissionActions:[],finalApprovalActions:[],finalRejectionActions:[]}});
const operators=["equals","not_equals","greater_than","less_than","is_empty","changed","changed_to"];
const uid=()=>`${Date.now()}_${Math.random().toString(16).slice(2)}`;

function Criteria({value,objectKey,onChange}){
 const rules=value?.rules||[]; const patch=(rules)=>onChange({...value,type:value?.type||"all",rules});
 return <div className="space-y-2 rounded-xl border border-slate-200 bg-slate-50 p-3">
  <div className="flex items-center justify-between"><b className="text-sm">Entry criteria</b><select className="rounded-lg border bg-white p-2 text-sm" value={value?.type||"all"} onChange={e=>onChange({...value,type:e.target.value})}><option value="all">All conditions</option><option value="any">Any condition</option></select></div>
  {rules.map((r,i)=><div key={r.id||i} className="grid gap-2 md:grid-cols-[1.4fr_.8fr_1fr_auto]"><MetadataResourcePicker objectKey={objectKey} value={r.field||""} label="Field" onChange={field=>patch(rules.map((x,j)=>j===i?{...x,field}:x))}/><label className="text-xs text-slate-600">Operator<select className="mt-1 w-full rounded-lg border bg-white p-2" value={r.operator||"equals"} onChange={e=>patch(rules.map((x,j)=>j===i?{...x,operator:e.target.value}:x))}>{operators.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs text-slate-600">Value<input className="mt-1 w-full rounded-lg border p-2" value={r.value??""} disabled={r.operator==="is_empty"} onChange={e=>patch(rules.map((x,j)=>j===i?{...x,value:e.target.value}:x))}/></label><button className="self-end rounded-lg border px-3 py-2 text-red-600" onClick={()=>patch(rules.filter((_,j)=>j!==i))}>×</button></div>)}
  <button className="text-sm text-blue-700" onClick={()=>patch([...rules,{id:uid(),field:"",operator:"equals",value:""}])}>+ Add condition</button>
 </div>;
}
function ActionLane({title,items,registry,onChange}){return <div className="rounded-xl border border-slate-200 p-3"><div className="flex items-center"><b className="text-sm">{title}</b><button className="ml-auto text-sm text-blue-700" onClick={()=>onChange([...items,{type:registry[0]?.key||"IN_APP_NOTIFICATION"}])}>+ Action</button></div>{items.map((a,i)=><div key={i} className="mt-2 flex gap-2"><select className="min-w-0 flex-1 rounded-lg border p-2 text-sm" value={a.type||a.key||""} onChange={e=>onChange(items.map((x,j)=>j===i?{...x,type:e.target.value}:x))}>{registry.map(x=><option key={x.key} value={x.key}>{x.displayName||x.key}</option>)}</select><button className="rounded-lg border px-3 text-red-600" onClick={()=>onChange(items.filter((_,j)=>j!==i))}>×</button></div>)}</div>}

export default function ApprovalProcessBuilder({onMessage,onError}){
 const [items,setItems]=useState([]),[objects,setObjects]=useState([]),[roles,setRoles]=useState([]),[actions,setActions]=useState([]),[form,setForm]=useState(blank()),[id,setId]=useState(null),[requests,setRequests]=useState([]);
 /* Core lists are required; peripheral lookups (pending queue, approver
    roles, action registry) fail SOFT — an optional endpoint that is absent
    or forbidden must not blank the whole builder. */
 const load=()=>Promise.all([apiRequest("/api/platform/approval-processes"),apiRequest("/api/platform/objects"),apiRequest("/api/platform/approval-requests?status=pending").catch(()=>({data:[]})),apiRequest("/api/platform/approval-roles").catch(()=>({data:[]})),apiRequest("/api/platform/workflow-actions").catch(()=>({data:[]}))]).then(([p,o,q,r,a])=>{if(p&&!p.success)throw new Error(p.message||"Unable to load approval processes");setItems(p.data||[]);setObjects(o.data?.objects||o.data||[]);setRequests(q.data||[]);setRoles(r.data||r||[]);setActions(a.data||a||[])}).catch(e=>onError?.(e.message)); useEffect(()=>{load()},[]);
 const selectedObject=useMemo(()=>objects.find(o=>o.id===form.objectId),[objects,form.objectId]); const objectKey=selectedObject?.object_key||selectedObject?.api_name||"";
 const open=async p=>{try{const r=await apiRequest(`/api/platform/approval-processes/${p.id}`);setId(p.id);setForm({...blank(),...r.data,objectId:r.data.object_id,config:{...blank().config,...(r.data.config||{})},steps:(r.data.steps||[]).map(s=>({...s,roleId:s.role_id,config:s.config||{}}))})}catch(e){onError?.(e.message)}};
 const save=async()=>{try{const payload={objectId:form.objectId,name:form.name,active:form.active,conditions:form.conditions,config:form.config,steps:form.steps.map(s=>({label:s.label,roleId:s.roleId,config:s.config||{}}))};const r=await apiRequest(id?`/api/platform/approval-processes/${id}`:"/api/platform/approval-processes",{method:id?"PUT":"POST",body:JSON.stringify(payload)});setId(r.data.id||id);await load();onMessage?.("Approval process saved.")}catch(e){onError?.(e.message)}};
 const setActionsFor=(key,next)=>setForm(f=>({...f,config:{...f.config,[key]:next}}));
 return <div className="space-y-4"><div className="flex items-center"><div><h2 className="text-xl font-semibold">Approval Builder</h2><p className="text-sm text-slate-500">Visual criteria → approvers → registered outcome actions.</p></div><button className="ml-auto onepos-btn onepos-btn-secondary" onClick={()=>{setId(null);setForm(blank())}}>New process</button></div>
 <div className="grid gap-4 lg:grid-cols-[230px_minmax(0,1fr)_280px]"><aside className="rounded-xl border bg-white p-3"><b>Processes</b>{items.map(p=><button className="mt-2 block w-full rounded-lg px-2 py-2 text-left text-sm hover:bg-slate-50" key={p.id} onClick={()=>open(p)}>{p.name}</button>)}</aside>
 <main className="space-y-4 rounded-xl border bg-white p-4"><div className="grid gap-3 md:grid-cols-2"><input className="rounded-lg border p-2" placeholder="Process name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select className="rounded-lg border p-2" value={form.objectId} onChange={e=>setForm({...form,objectId:e.target.value})}><option value="">Select object</option>{objects.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></div>
 <Criteria value={form.conditions} objectKey={objectKey} onChange={conditions=>setForm({...form,conditions})}/>
 <section className="rounded-xl border border-slate-200 p-3"><div className="flex"><b className="text-sm">Approval path</b><button className="ml-auto text-sm text-blue-700" onClick={()=>setForm({...form,steps:[...form.steps,{label:"Approval",roleId:"",config:{}}]})}>+ Approver</button></div>{form.steps.map((s,i)=><div draggable onDragStart={e=>e.dataTransfer.setData("approval-step",String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{const from=Number(e.dataTransfer.getData("approval-step"));if(Number.isNaN(from)||from===i)return;const next=[...form.steps];const [m]=next.splice(from,1);next.splice(i,0,m);setForm({...form,steps:next})}} key={i} className="mt-2 grid grid-cols-[32px_1fr_1fr_auto] items-center gap-2 rounded-xl border bg-slate-50 p-2"><span className="text-center text-slate-400">⋮⋮</span><input className="rounded-lg border p-2" value={s.label} onChange={e=>setForm({...form,steps:form.steps.map((x,j)=>j===i?{...x,label:e.target.value}:x)})}/><select className="rounded-lg border p-2" value={s.roleId} onChange={e=>setForm({...form,steps:form.steps.map((x,j)=>j===i?{...x,roleId:e.target.value}:x)})}><option value="">Approver role</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name||r.label}</option>)}</select><button className="text-red-700" onClick={()=>setForm({...form,steps:form.steps.filter((_,j)=>j!==i)})}>×</button></div>)}</section>
 <div className="grid gap-3 xl:grid-cols-3"><ActionLane title="On submission" items={form.config.submissionActions||[]} registry={actions} onChange={v=>setActionsFor("submissionActions",v)}/><ActionLane title="On approval" items={form.config.finalApprovalActions||[]} registry={actions} onChange={v=>setActionsFor("finalApprovalActions",v)}/><ActionLane title="On rejection" items={form.config.finalRejectionActions||[]} registry={actions} onChange={v=>setActionsFor("finalRejectionActions",v)}/></div>
 <div className="flex flex-wrap gap-4">{[["lockRecord","Lock while pending"],["allowReassign","Allow reassignment"],["requireCommentOnReject","Require rejection comment"]].map(([k,l])=><label key={k} className="text-sm"><input type="checkbox" checked={form.config?.[k]!==false} onChange={e=>setForm({...form,config:{...form.config,[k]:e.target.checked}})}/> {l}</label>)}<label className="ml-auto text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label></div><button className="onepos-btn onepos-btn-primary" onClick={save}>Save approval process</button></main>
 <aside className="rounded-xl border bg-white p-3"><b>Pending approvals</b>{requests.map(q=><div key={q.id} className="mt-2 rounded-lg border p-2 text-sm"><b>{q.process_name}</b><div className="text-slate-500">{q.step_label}</div><div className="text-xs">Record {q.record_id}</div></div>)}{!requests.length&&<p className="mt-2 text-sm text-slate-500">No pending approvals.</p>}</aside></div></div>;
}
