import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "../../../services/api.js";
import { Toggle } from "../../../components/ui.jsx";
const TYPES=["CREATE_RECORD","UPDATE_RECORD","CREATE_RELATED_RECORD","UPDATE_RELATED_RECORD","CONDITION","IN_APP_NOTIFICATION","SEND_EMAIL","SEND_SMS","SEND_WHATSAPP","CALL_FUNCTION","RUN_SUBFLOW","WAIT","STOP"];
/* Human labels for element/trigger machine keys — the payload still stores
   the raw keys, only the presentation is translated. */
const TYPE_LABELS={CREATE_RECORD:"Create record",UPDATE_RECORD:"Update record",CREATE_RELATED_RECORD:"Create related record",UPDATE_RELATED_RECORD:"Update related record",CONDITION:"Condition (branch)",IN_APP_NOTIFICATION:"In-app notification",SEND_EMAIL:"Send email",SEND_SMS:"Send SMS",SEND_WHATSAPP:"Send WhatsApp",CALL_FUNCTION:"Call function",RUN_SUBFLOW:"Run subflow",WAIT:"Wait",STOP:"Stop"};
const TRIGGER_LABELS={before_create:"Before a record is created",after_create:"After a record is created",before_update:"Before a record is updated",after_update:"After a record is updated",before_delete:"Before a record is deleted",after_delete:"After a record is deleted",field_changed:"When a field changes",manual:"Manual trigger"};
const typeLabel=t=>TYPE_LABELS[t]||t;
const triggerLabel=t=>TRIGGER_LABELS[t]||t;
const uid=()=>`node_${Date.now()}_${Math.random().toString(16).slice(2)}`;
export default function VisualFlowBuilder({onMessage,onError}){
 const [rules,setRules]=useState([]),[objects,setObjects]=useState([]),[flow,setFlow]=useState({name:"",objectKey:"",triggerKey:"after_update",active:false,nodes:[]}),[id,setId]=useState(null),[selected,setSelected]=useState(null);
 const load=()=>Promise.all([apiRequest("/api/platform/rules"),apiRequest("/api/platform/objects")]).then(([r,o])=>{setRules((r.data||[]).filter(x=>x.action?.type==="workflow"));setObjects(o.data||[])}).catch(e=>onError?.(e.message)); useEffect(()=>{load()},[]);
 const open=r=>{setId(r.id);setFlow({name:r.name,objectKey:r.object_key||"",triggerKey:r.trigger_key,active:r.active!==false,nodes:(r.action?.actions||[]).map((a,i)=>({id:uid(),type:a.type||a.key,label:(a.label&&a.label!==(a.type||a.key))?a.label:typeLabel(a.type||a.key),config:{...a},x:120+(i%3)*260,y:80+Math.floor(i/3)*150}))});};
 const add=type=>setFlow(f=>({...f,nodes:[...f.nodes,{id:uid(),type,label:typeLabel(type),config:{},x:120+(f.nodes.length%3)*260,y:80+Math.floor(f.nodes.length/3)*150}]}));
 const node=useMemo(()=>flow.nodes.find(n=>n.id===selected),[flow,selected]); const patch=(p)=>setFlow(f=>({...f,nodes:f.nodes.map(n=>n.id===selected?{...n,...p,config:{...n.config,...(p.config||{})}}:n)}));
 const save=async()=>{try{const payload={name:flow.name,objectKey:flow.objectKey||null,triggerKey:flow.triggerKey,conditions:[],active:flow.active,action:{type:"workflow",match:"all",actions:flow.nodes.map(n=>({type:n.type,...n.config,_visual:{x:n.x,y:n.y,label:n.label}}))}};const r=await apiRequest(id?`/api/platform/rules/${id}`:"/api/platform/rules",{method:id?"PUT":"POST",body:JSON.stringify(payload)});setId(r.data.id);await load();onMessage?.("Flow saved.")}catch(e){onError?.(e.message)}};
 return <div className="space-y-4 min-w-0"><div className="flex flex-wrap gap-2 items-center"><h2 className="text-xl font-semibold mr-auto">Visual Flow Builder</h2><input className="onepos-input w-auto" placeholder="Flow name" value={flow.name} onChange={e=>setFlow({...flow,name:e.target.value})}/><select className="onepos-input w-auto" value={flow.objectKey} onChange={e=>setFlow({...flow,objectKey:e.target.value})}><option value="">No object</option>{objects.map(o=><option key={o.id} value={o.object_key}>{o.label}</option>)}</select><select className="onepos-input w-auto" value={flow.triggerKey} onChange={e=>setFlow({...flow,triggerKey:e.target.value})}>{["before_create","after_create","before_update","after_update","before_delete","after_delete","field_changed","manual"].map(x=><option key={x} value={x}>{triggerLabel(x)}</option>)}</select><label className="flex items-center gap-2 text-sm"><Toggle checked={flow.active} onChange={e=>setFlow({...flow,active:e.target.checked})} aria-label="Flow active"/> Active</label><button className="onepos-btn onepos-btn-primary" onClick={save}>Save</button></div>
 <div className="grid lg:grid-cols-[210px_minmax(0,1fr)_270px] gap-4"><aside className="onepos-card p-3 min-w-0"><b className="block mb-1">Elements</b>{TYPES.map(t=><button key={t} onClick={()=>add(t)} className="mt-2 block w-full rounded border px-2 py-2 text-left text-xs" title={typeLabel(t)}>+ {typeLabel(t)}</button>)}<hr className="my-3"/><b className="block mb-1">Saved flows</b>{rules.map(r=><button key={r.id} onClick={()=>open(r)} className="mt-2 block w-full text-left text-sm text-blue-700 truncate" title={r.name}>{r.name}</button>)}</aside>
 <div className="relative min-h-[650px] overflow-auto rounded border p-8 min-w-0" style={{background:"var(--onepos-surface-muted)",borderColor:"var(--onepos-border)"}}>{flow.nodes.map((n,i)=><div key={n.id} style={{position:"absolute",left:n.x,top:n.y,width:210}} className={`rounded-lg border bg-white p-3 shadow-sm ${selected===n.id?"ring-2 ring-blue-500":""}`} onClick={()=>setSelected(n.id)}><div className="text-xs text-slate-400 truncate">{i===0?"Start → ":"↓ "}{typeLabel(n.type)}</div><b className="text-sm break-words">{n.label}</b></div>)}</div>
 <aside className="onepos-card p-3 min-w-0">{node?<div className="space-y-3"><b className="block">Node properties</b><input className="onepos-input" value={node.label} onChange={e=>patch({label:e.target.value})}/><textarea className="onepos-input font-mono text-xs" rows="14" value={JSON.stringify(node.config,null,2)} onChange={e=>{try{patch({config:JSON.parse(e.target.value)})}catch{}}}/><div className="grid grid-cols-2 gap-2"><input type="number" className="onepos-input" value={node.x} onChange={e=>patch({x:Number(e.target.value)})}/><input type="number" className="onepos-input" value={node.y} onChange={e=>patch({y:Number(e.target.value)})}/></div><button className="text-red-700 text-sm" onClick={()=>{setFlow(f=>({...f,nodes:f.nodes.filter(n=>n.id!==selected)}));setSelected(null)}}>Delete node</button></div>:<span className="text-sm text-slate-500">Select a node to configure it.</span>}</aside></div></div>;
}
