import PlatformExtensionFields from "../../components/platform/PlatformExtensionFields.jsx";
import { useState } from "react";
import { X } from "lucide-react";

export default function SupplierFormModal({ supplier, onClose, onSave }) {
  const [platform, setPlatform] = useState(null);
  const [platformReady, setPlatformReady] = useState(false);
  const [form, setForm] = useState({ id: supplier.id, name: supplier.name || "", phone: supplier.phone || "", email: supplier.email || "", address: supplier.address || "", notes: supplier.notes || "" });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const submit = async (event) => { event.preventDefault(); if (!platformReady) return; if (!form.name.trim()) { setError("Supplier name is required."); return; } try { setSaving(true); await onSave({ ...form, platform, name: form.name.trim() }); } catch (err) { setError(err.message || "Unable to save supplier"); } finally { setSaving(false); } };
  return <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"><div className="bg-white rounded-xl w-[560px] max-w-full shadow-2xl"><div className="p-5 border-b flex items-center justify-between"><h2 className="font-bold text-xl">{supplier.id ? "Edit Supplier" : "Add Supplier"}</h2><button onClick={onClose} disabled={saving} className="p-2 hover:bg-slate-100 rounded" title="Close"><X size={20} /></button></div><form onSubmit={submit} className="p-5">{error && <div className="mb-4 px-3 py-2 bg-red-50 border border-red-200 text-red-700 rounded text-sm">{error}</div>}<div className="grid grid-cols-2 gap-4">{[["name", "Name *"], ["phone", "Phone"], ["email", "Email"], ["address", "Address"], ["notes", "Notes"]].map(([field, label]) => <label key={field} className={`text-sm text-slate-600 ${field === "address" || field === "notes" ? "col-span-2" : ""}`}><span className="block mb-1 font-medium">{label}</span>{field === "address" || field === "notes" ? <textarea rows="2" value={form[field]} onChange={(event) => update(field, event.target.value)} className="w-full px-3 py-2 border border-slate-200 rounded-lg resize-none" /> : <input required={field === "name"} type={field === "email" ? "email" : "text"} value={form[field]} onChange={(event) => update(field, event.target.value)} className="w-full h-10 px-3 border border-slate-200 rounded-lg" />}</label>)}</div><PlatformExtensionFields objectKey="supplier" recordId={supplier.id} coreValues={form} onChange={setPlatform} onReady={setPlatformReady} /><div className="flex justify-end gap-2 mt-6 pt-4 border-t"><button type="button" onClick={onClose} disabled={saving} className="h-10 px-4 border rounded-lg text-sm">Cancel</button><button type="submit" disabled={saving || !platformReady} className="h-10 px-5 bg-blue-600 text-white rounded-lg text-sm font-medium">{saving ? "Saving..." : "Save supplier"}</button></div></form></div></div>;
}
